### ISSUE TITLE
getting an error

### ISSUE THREAD

**Issue by Attakhan99** [sstokic-tgm/Gladiatorcheatz-Public#2]
http://prntscr.com/g1plrc

**Comment by sstokic-tgm** [comment]
As the README.md states, you have to adjust the DX9 path in the project settings..

**Comment by Attakhan99** [comment]
can u post screenshots of it so we know how to do it thats gonna be very usefull :)

**Comment by sstokic-tgm** [comment]
There is a post on uc, about it: https://www.unknowncheats.me/forum/1774202-post30.html
