### ISSUE TITLE
Can it support UTF-8?

### ISSUE THREAD

**Issue by kurobaryo** [sstokic-tgm/Gladiatorcheatz-Public#5]
I really love your project, how ever when i'm trying to translate it into Japanese, it appears "???". And i search imgui SDK you are using to build the ui, however i have no idea how to change it into UTF-8, because i see `ui_font = p_Surface->fontCreate();
			p_Surface->setFontGlyphSet(ui_font, XorStr("msyh"), 14, 350, 0, 0, FONTFLAG_OUTLINE);`
instead of `ImGuiIO& io = ImGui::GetIO();
io.Fonts->AddFontFromFileTTF("ArialUni.ttf", 18.0f, NULL, io.Fonts->GetGlyphRangesJapanese());`. Any solutions? Btw, I'm willing to contribute a translation of Japanese.

**Comment by sstokic-tgm** [comment]
Puh bro, I didn't look that much into that how you can add UTF-8 support to the menu font. I was trying smth but it didn't work well. As I know AimTux loads additional fonts for their menu, you can look there how they do it
