### ISSUE TITLE
Alt key isnt working for Aim/Triggerbot key.

### ISSUE THREAD

**Issue by tempacc123** [sstokic-tgm/Gladiatorcheatz-Public#7]
I really dont have idea why it isnt working.

I set it to proper vk_key, confirmed other keys (M1) is working for Aimkey but the Alt key isnt working as aim/triggerbot key.

What am i missing? i really have no idea.

**Comment by sstokic-tgm** [comment]
Maybe the ALT-key is used for smth else?

**Comment by tempacc123** [comment]
Like, What? as i told you i really have no idea.

**Comment by sstokic-tgm** [comment]
I mean, that the ALT-key is already binded in csgo for smth else, or your OS doesn't let you use the key or you maybe just missed it by one index when you were adding it

**Comment by tempacc123** [comment]
ALT key being pressed will return WM_SYSKEYDOWN NOT WM_KEYDOWN because it is a system related key : P

https://msdn.microsoft.com/en-us/library/windows/desktop/ms646286(v=vs.85).aspx

so, adding this codes to wndproc_h function solves it.

	case WM_SYSKEYDOWN:
		if (wParam == VK_MENU)
			pressedKey[VK_MENU] = true;
		break;

	case WM_SYSKEYUP:
		if (wParam == VK_MENU)
			pressedKey[VK_MENU] = false;
		break;

another problem is when i alt+tap windows to csgo it still thinks i am pressing alt lmao.
kinda annoying coz of this
